services:
  - type: web
    name: tradelink
    env: python
    runtime: python3
    buildCommand: |
      pip install -U pip setuptools wheel
      pip install --no-cache-dir -r requirements.txt
    startCommand: |
      python -m gunicorn app:app \
        --timeout 180 \
        --workers 1 \
        --worker-class eventlet \
        --log-level debug \
        --preload \
        --access-logfile - \
        --error-logfile -
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: PORT
        value: "8000"
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PIP_NO_CACHE_DIR
        value: "true"
      - key: PYTHONPATH
        value: "/opt/render/project/src"
    healthCheckPath: /
    autoDeploy: true