services:
  - type: web
    name: tradelink
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      python -m pip install wheel setuptools<81.0.0
      python -m pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 2 --worker-class eventlet --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: PORT
        value: "8000"
    healthCheckPath: /
    autoDeploy: true