services:
  - type: web
    name: tradelink
    env: python
    plan: free
    runtime: python3
    buildCommand: |
      python -m pip install --upgrade pip
      python -m pip install setuptools wheel
      python -m pip install --no-cache-dir -r requirements.txt
    startCommand: |
      gunicorn app:app \
        --bind 0.0.0.0:$PORT \
        --timeout 120 \
        --workers 1 \
        --worker-class eventlet \
        --log-level info \
        --access-logfile - \
        --error-logfile - \
        --capture-output
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PIP_NO_CACHE_DIR
        value: "true"
      - key: PYTHONPATH
        value: "/opt/render/project/src"
      - key: FLASK_DEBUG
        value: "0"
      - key: GUNICORN_CMD_ARGS
        value: "--timeout 120 --workers 1 --worker-class eventlet --log-level info"
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1